# Generated by Django 4.2 on 2024-08-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_tax_order_discounts_order_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='curreny',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
