# Generated by Django 4.2 on 2024-08-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_curreny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='curreny',
            new_name='currency',
        ),
    ]
